name: school-score-monitoring (develop)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
permissions:
  checks: write
  contents: write
jobs:
  clean:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: |
          npm install
      - name: Run prettier
        run: |
          npm run format
      - name: Save changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git diff-index --quiet HEAD || (git commit -a -m'[Bot] update: apply changes' && git push -f) || echo "No changes to commit"